language: r
dist: trusty
sudo: required

branches:
  only:
    - dev
    - master

notifications:
  slack:
      rooms: insileco:bSFo4jHeKnaM4WobzJJ8DTPj
      template:
        - "%{repository} (%{commit}) : %{message} %{foo} "
        - "Build: %{build_url}"
        - "website: https://insileco.github.io/"
        - "duration: %{duration}"

cache:
  packages: yes
  directories:
    - $HOME/bin

apt_packages:
  - libgdal-dev
  - libgeos-dev
  - libproj-dev
  - libudunits2-dev
  - libfreetype6-dev
  - libpoppler-cpp-dev
  - libssl-dev

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - mkdir pandoc
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb
  - export PATH=./pandoc/usr/bin/:$PATH

script:
  - sh build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: dev
